version: '3'

services:
  mysql_serv:
    container_name: mysql_server
    restart: always
    image: mysql
    environment:
      MYSQL_DATABASE: 'wikigraphstats'
      MYSQL_ROOT_PASSWORD: totalrandompassword
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db-data:/var/lib/mysql
volumes:
    my-db-data:
